-- V22.7.0 인증·원자성 필수 마이그레이션
-- 적용 전 Supabase 백업을 생성하고 V22.6.8 무결성 마이그레이션을 먼저 적용하세요.

begin;

create table if not exists public.accountbook_user_identities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  provider text not null check (provider in ('local', 'kakao')),
  provider_subject text not null,
  login_name text,
  credential_hash text,
  credential_salt text,
  credential_iterations integer,
  credential_version integer not null default 1,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  unique (provider, provider_subject),
  unique (provider, user_id)
);

create table if not exists public.accountbook_user_security (
  user_id uuid primary key references public.users(id) on delete cascade,
  session_version integer not null default 1,
  password_changed_at timestamptz,
  updated_at timestamptz not null default clock_timestamp()
);

create table if not exists public.accountbook_admin_security (
  singleton boolean primary key default true check (singleton),
  password_hash text,
  password_salt text,
  password_iterations integer,
  password_version integer not null default 1,
  session_version integer not null default 1,
  updated_at timestamptz not null default clock_timestamp()
);

insert into public.accountbook_admin_security(singleton)
values (true)
on conflict (singleton) do nothing;

create table if not exists public.accountbook_auth_attempts (
  attempt_key text primary key,
  window_started_at timestamptz not null default clock_timestamp(),
  attempts integer not null default 0,
  blocked_until timestamptz,
  updated_at timestamptz not null default clock_timestamp()
);

create table if not exists public.accountbook_transaction_audit (
  id bigint generated by default as identity primary key,
  transaction_id uuid,
  household_id uuid not null,
  actor_user_id uuid,
  actor_kind text not null default 'user',
  action text not null check (action in ('update', 'delete', 'bulk_update')),
  before_value jsonb,
  after_value jsonb,
  created_at timestamptz not null default clock_timestamp()
);

create index if not exists accountbook_transaction_audit_household_created_idx
on public.accountbook_transaction_audit(household_id, created_at desc);

alter table public.accountbook_user_identities enable row level security;
alter table public.accountbook_user_security enable row level security;
alter table public.accountbook_admin_security enable row level security;
alter table public.accountbook_auth_attempts enable row level security;
alter table public.accountbook_transaction_audit enable row level security;

revoke all on table public.accountbook_user_identities from public, anon, authenticated;
revoke all on table public.accountbook_user_security from public, anon, authenticated;
revoke all on table public.accountbook_admin_security from public, anon, authenticated;
revoke all on table public.accountbook_auth_attempts from public, anon, authenticated;
revoke all on table public.accountbook_transaction_audit from public, anon, authenticated;

grant select, insert, update, delete on table public.accountbook_user_identities to service_role;
grant select, insert, update, delete on table public.accountbook_user_security to service_role;
grant select, insert, update, delete on table public.accountbook_admin_security to service_role;
grant select, insert, update, delete on table public.accountbook_auth_attempts to service_role;
grant select, insert, update, delete on table public.accountbook_transaction_audit to service_role;
grant usage, select on sequence public.accountbook_user_identities_id_seq to service_role;
grant usage, select on sequence public.accountbook_transaction_audit_id_seq to service_role;

create or replace function public.accountbook_auth_attempt(
  p_key text,
  p_limit integer default 8,
  p_window_seconds integer default 900,
  p_success boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_limit integer := least(50, greatest(3, coalesce(p_limit, 8)));
  v_window integer := least(86400, greatest(60, coalesce(p_window_seconds, 900)));
  v_row public.accountbook_auth_attempts%rowtype;
begin
  if nullif(btrim(coalesce(p_key, '')), '') is null then
    raise exception 'attempt key is required';
  end if;

  if p_success then
    delete from public.accountbook_auth_attempts where attempt_key = left(p_key, 180);
    return jsonb_build_object('allowed', true, 'attempts', 0, 'blocked_until', null);
  end if;

  insert into public.accountbook_auth_attempts(attempt_key, window_started_at, attempts, blocked_until, updated_at)
  values (left(p_key, 180), v_now, 1, null, v_now)
  on conflict (attempt_key) do update
  set window_started_at = case
        when public.accountbook_auth_attempts.window_started_at < v_now - make_interval(secs => v_window) then v_now
        else public.accountbook_auth_attempts.window_started_at
      end,
      attempts = case
        when public.accountbook_auth_attempts.window_started_at < v_now - make_interval(secs => v_window) then 1
        else public.accountbook_auth_attempts.attempts + 1
      end,
      blocked_until = case
        when public.accountbook_auth_attempts.window_started_at >= v_now - make_interval(secs => v_window)
             and public.accountbook_auth_attempts.attempts + 1 > v_limit
          then v_now + make_interval(secs => v_window)
        else public.accountbook_auth_attempts.blocked_until
      end,
      updated_at = v_now
  returning * into v_row;

  delete from public.accountbook_auth_attempts
  where updated_at < v_now - interval '30 days';

  return jsonb_build_object(
    'allowed', coalesce(v_row.blocked_until <= v_now, true) and v_row.attempts <= v_limit,
    'attempts', v_row.attempts,
    'blocked_until', v_row.blocked_until
  );
end;
$$;

create or replace function public.accountbook_create_local_user_v227(
  p_login_name text,
  p_nickname text,
  p_credential_hash text,
  p_credential_salt text,
  p_credential_iterations integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_login text := lower(regexp_replace(btrim(coalesce(p_login_name, '')), '\s+', ' ', 'g'));
  v_nickname text := left(btrim(coalesce(p_nickname, '')), 80);
  v_user public.users%rowtype;
begin
  if char_length(v_login) < 2 or char_length(v_login) > 80 then raise exception 'invalid_login_name'; end if;
  if char_length(coalesce(p_credential_hash, '')) < 20
     or char_length(coalesce(p_credential_salt, '')) < 16
     or coalesce(p_credential_iterations, 0) < 100000 then
    raise exception 'invalid_credential';
  end if;
  if v_nickname = '' then v_nickname := left(p_login_name, 80); end if;

  if exists (
    select 1 from public.accountbook_user_identities
    where provider = 'local' and provider_subject = v_login
  ) then raise exception 'login_name_in_use'; end if;

  insert into public.users(kakao_user_key, nickname)
  values (left('local_account:' || gen_random_uuid()::text, 160), v_nickname)
  returning * into v_user;

  insert into public.accountbook_user_identities(
    user_id, provider, provider_subject, login_name,
    credential_hash, credential_salt, credential_iterations, credential_version
  ) values (
    v_user.id, 'local', v_login, left(p_login_name, 80),
    p_credential_hash, p_credential_salt, p_credential_iterations, 2
  );
  insert into public.accountbook_user_security(user_id, session_version, password_changed_at)
  values (v_user.id, 1, clock_timestamp())
  on conflict (user_id) do nothing;

  return jsonb_build_object(
    'id', v_user.id,
    'kakao_user_key', v_user.kakao_user_key,
    'nickname', v_user.nickname
  );
end;
$$;

create or replace function public.accountbook_set_local_identity_v227(
  p_user_id uuid,
  p_login_name text,
  p_credential_hash text,
  p_credential_salt text,
  p_credential_iterations integer,
  p_revoke_sessions boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_login text := lower(regexp_replace(btrim(coalesce(p_login_name, '')), '\s+', ' ', 'g'));
  v_session_version integer := 1;
begin
  perform 1 from public.users where id = p_user_id for update;
  if not found then raise exception 'user_not_found'; end if;
  if char_length(v_login) < 2 or char_length(v_login) > 80 then raise exception 'invalid_login_name'; end if;
  if char_length(coalesce(p_credential_hash, '')) < 20
     or char_length(coalesce(p_credential_salt, '')) < 16
     or coalesce(p_credential_iterations, 0) < 100000 then
    raise exception 'invalid_credential';
  end if;
  if exists (
    select 1 from public.accountbook_user_identities
    where provider = 'local' and provider_subject = v_login and user_id <> p_user_id
  ) then raise exception 'login_name_in_use'; end if;

  insert into public.accountbook_user_identities(
    user_id, provider, provider_subject, login_name,
    credential_hash, credential_salt, credential_iterations, credential_version, updated_at
  ) values (
    p_user_id, 'local', v_login, left(p_login_name, 80),
    p_credential_hash, p_credential_salt, p_credential_iterations, 2, clock_timestamp()
  )
  on conflict (provider, user_id) do update
  set provider_subject = excluded.provider_subject,
      login_name = excluded.login_name,
      credential_hash = excluded.credential_hash,
      credential_salt = excluded.credential_salt,
      credential_iterations = excluded.credential_iterations,
      credential_version = excluded.credential_version,
      updated_at = clock_timestamp();

  insert into public.accountbook_user_security(user_id, session_version, password_changed_at, updated_at)
  values (p_user_id, 1, clock_timestamp(), clock_timestamp())
  on conflict (user_id) do update
  set session_version = case
        when coalesce(p_revoke_sessions, true) then public.accountbook_user_security.session_version + 1
        else public.accountbook_user_security.session_version
      end,
      password_changed_at = clock_timestamp(),
      updated_at = clock_timestamp()
  returning session_version into v_session_version;

  return jsonb_build_object('saved', true, 'session_version', v_session_version, 'login_name', v_login);
end;
$$;

create or replace function public.accountbook_link_kakao_identity_v227(
  p_user_id uuid,
  p_kakao_id text,
  p_nickname text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_subject text := btrim(coalesce(p_kakao_id, ''));
begin
  perform 1 from public.users where id = p_user_id for update;
  if not found then raise exception 'user_not_found'; end if;
  if v_subject = '' or char_length(v_subject) > 160 then raise exception 'invalid_kakao_id'; end if;
  if exists (
    select 1 from public.accountbook_user_identities
    where provider = 'kakao' and provider_subject = v_subject and user_id <> p_user_id
  ) then raise exception 'kakao_identity_in_use'; end if;

  insert into public.accountbook_user_identities(user_id, provider, provider_subject, login_name, updated_at)
  values (p_user_id, 'kakao', v_subject, left(coalesce(p_nickname, ''), 80), clock_timestamp())
  on conflict (provider, user_id) do update
  set provider_subject = excluded.provider_subject,
      login_name = excluded.login_name,
      updated_at = clock_timestamp();
  insert into public.accountbook_user_security(user_id, session_version)
  values (p_user_id, 1)
  on conflict (user_id) do nothing;
  return jsonb_build_object('linked', true);
end;
$$;

create or replace function public.accountbook_purge_household_v227(p_household_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_transactions integer := 0;
  v_members integer := 0;
  v_households integer := 0;
begin
  perform 1 from public.households where id = p_household_id for update;
  if not found then raise exception 'household_not_found'; end if;

  if to_regclass('public.accountbook_budgets') is not null then
    execute 'delete from public.accountbook_budgets where household_id = $1' using p_household_id;
  end if;
  if to_regclass('public.accountbook_recurring') is not null then
    execute 'delete from public.accountbook_recurring where household_id = $1' using p_household_id;
  end if;
  if to_regclass('public.accountbook_categories') is not null then
    execute 'delete from public.accountbook_categories where household_id = $1' using p_household_id;
  end if;
  if to_regclass('public.accountbook_meme_cards') is not null then
    execute 'delete from public.accountbook_meme_cards where household_id = $1' using p_household_id;
  end if;

  delete from public.accountbook_transaction_audit where household_id = p_household_id;
  delete from public.accountbook_settings
  where key in (
    'custom_categories:' || p_household_id::text,
    'category_keywords:' || p_household_id::text,
    'payment_assets:' || p_household_id::text,
    'asset_history:' || p_household_id::text,
    'reserve_plans:' || p_household_id::text,
    'member_aliases:' || p_household_id::text,
    'transaction_edit_history:' || p_household_id::text,
    'settlement_history:' || p_household_id::text,
    'free_report_preference:' || p_household_id::text
  )
  or left(key, char_length('budgets:' || p_household_id::text || ':'))
       = 'budgets:' || p_household_id::text || ':'
  or left(key, char_length('free_report_snapshot:' || p_household_id::text || ':'))
       = 'free_report_snapshot:' || p_household_id::text || ':'
  or left(key, char_length('kakao_edit_v2254:' || p_household_id::text || ':'))
       = 'kakao_edit_v2254:' || p_household_id::text || ':'
  or (
    left(key, char_length('kakao_cta_v215:')) = 'kakao_cta_v215:'
    and strpos(key, ':' || p_household_id::text || ':') > 0
  )
  or (
    left(key, char_length('kakao_selected_household_v2251:')) = 'kakao_selected_household_v2251:'
    and btrim(coalesce(value, '')) = p_household_id::text
  )
  or exists (
    select 1
    from public.household_members hm
    where hm.household_id = p_household_id
      and left(key, char_length('kakao_flow_v215:' || hm.user_id::text || ':'))
          = 'kakao_flow_v215:' || hm.user_id::text || ':'
  );

  delete from public.transactions where household_id = p_household_id;
  get diagnostics v_transactions = row_count;
  delete from public.household_members where household_id = p_household_id;
  get diagnostics v_members = row_count;
  delete from public.households where id = p_household_id;
  get diagnostics v_households = row_count;

  return jsonb_build_object(
    'deleted', v_households = 1,
    'transactions', v_transactions,
    'members', v_members
  );
end;
$$;

create or replace function public.accountbook_replace_budget_plan_v227(
  p_household_id uuid,
  p_month text,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer := 0;
begin
  if p_month !~ '^20[0-9]{2}-(0[1-9]|1[0-2])$' then raise exception 'invalid_month'; end if;
  if jsonb_typeof(coalesce(p_rows, '[]'::jsonb)) <> 'array' then raise exception 'rows_must_be_array'; end if;
  if jsonb_array_length(coalesce(p_rows, '[]'::jsonb)) > 100 then raise exception 'too_many_budget_rows'; end if;
  if to_regclass('public.accountbook_budgets') is null then raise exception 'accountbook_budgets_required'; end if;

  delete from public.accountbook_budgets where household_id = p_household_id and month = p_month;
  insert into public.accountbook_budgets(household_id, month, category, amount)
  select p_household_id,
         p_month,
         left(btrim(item->>'category'), 80),
         greatest(0, least(2000000000, round((item->>'amount')::numeric)))
  from jsonb_array_elements(coalesce(p_rows, '[]'::jsonb)) item
  where nullif(btrim(item->>'category'), '') is not null
    and coalesce((item->>'amount')::numeric, 0) > 0;
  get diagnostics v_count = row_count;

  delete from public.accountbook_settings where key = 'budgets:' || p_household_id::text || ':' || p_month;
  return jsonb_build_object('saved', v_count);
end;
$$;

create or replace function public.accountbook_apply_recurring_v227(
  p_household_id uuid,
  p_month text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer := 0;
  v_invalid integer := 0;
begin
  if p_month !~ '^20[0-9]{2}-(0[1-9]|1[0-2])$' then raise exception 'invalid_month'; end if;
  if to_regclass('public.accountbook_recurring') is null then raise exception 'accountbook_recurring_required'; end if;

  select count(*) into v_invalid
  from public.accountbook_recurring r
  left join public.household_members hm
    on hm.household_id = r.household_id and hm.user_id = r.user_id
  where r.household_id = p_household_id
    and coalesce(r.is_active, true)
    and coalesce(r.last_applied_month, '') <> p_month
    and (r.user_id is null or hm.user_id is null or hm.role in ('blocked', 'pending'));
  if v_invalid > 0 then raise exception 'recurring_spender_required'; end if;

  insert into public.transactions(
    household_id, user_id, type, amount, category, memo, payment_method,
    transaction_date, source, raw_text
  )
  select r.household_id,
         r.user_id,
         case when r.type = 'income' then 'income' else 'expense' end,
         r.amount,
         r.category,
         r.memo,
         r.payment_method,
         make_date(
           split_part(p_month, '-', 1)::integer,
           split_part(p_month, '-', 2)::integer,
           least(28, greatest(1, coalesce(r.day_of_month, 1)))
         ),
         'recurring_auto',
         'recurring:' || r.id::text || ':' || p_month
  from public.accountbook_recurring r
  where r.household_id = p_household_id
    and coalesce(r.is_active, true)
    and coalesce(r.last_applied_month, '') <> p_month
  on conflict do nothing;
  get diagnostics v_count = row_count;

  update public.accountbook_recurring
  set last_applied_month = p_month
  where household_id = p_household_id
    and coalesce(is_active, true)
    and coalesce(last_applied_month, '') <> p_month;

  return jsonb_build_object('inserted', v_count);
end;
$$;

create or replace function public.accountbook_merge_users_v227(
  p_primary_user_id uuid,
  p_secondary_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_transactions integer := 0;
begin
  if p_primary_user_id = p_secondary_user_id then raise exception 'same_user'; end if;
  perform 1 from public.users where id = p_primary_user_id for update;
  if not found then raise exception 'primary_user_not_found'; end if;
  perform 1 from public.users where id = p_secondary_user_id for update;
  if not found then raise exception 'secondary_user_not_found'; end if;

  insert into public.household_members(household_id, user_id, role, created_at)
  select household_id, p_primary_user_id, role, created_at
  from public.household_members
  where user_id = p_secondary_user_id
  on conflict (household_id, user_id) do update
  set role = case
    when (case excluded.role when 'owner' then 60 when 'admin' then 50 when 'member' then 40 when 'viewer' then 30 when 'pending' then 20 else 10 end)
       > (case public.household_members.role when 'owner' then 60 when 'admin' then 50 when 'member' then 40 when 'viewer' then 30 when 'pending' then 20 else 10 end)
      then excluded.role else public.household_members.role end;

  update public.transactions set user_id = p_primary_user_id where user_id = p_secondary_user_id;
  get diagnostics v_transactions = row_count;
  if to_regclass('public.accountbook_recurring') is not null then
    execute 'update public.accountbook_recurring set user_id = $1 where user_id = $2'
    using p_primary_user_id, p_secondary_user_id;
  end if;

  delete from public.accountbook_user_identities s
  where s.user_id = p_secondary_user_id
    and exists (
      select 1 from public.accountbook_user_identities p
      where p.user_id = p_primary_user_id and p.provider = s.provider
    );
  update public.accountbook_user_identities
  set user_id = p_primary_user_id, updated_at = clock_timestamp()
  where user_id = p_secondary_user_id;

  delete from public.household_members where user_id = p_secondary_user_id;
  delete from public.accountbook_user_security where user_id = p_secondary_user_id;
  insert into public.accountbook_settings(key, value)
  values (
    left('identity_merge_redirect:' || p_secondary_user_id::text, 180),
    jsonb_build_object(
      'primary_user_id', p_primary_user_id,
      'secondary_user_id', p_secondary_user_id,
      'merged_at', clock_timestamp(),
      'version', 'V22.7.0-AUTH-ATOMICITY-STABILITY'
    )::text
  )
  on conflict (key) do update set value = excluded.value;

  update public.users
  set kakao_user_key = left('merged:' || p_secondary_user_id::text || ':' || extract(epoch from clock_timestamp())::bigint, 160),
      nickname = left(coalesce(nickname, '이전 계정') || ' (통합됨)', 80)
  where id = p_secondary_user_id;

  return jsonb_build_object('merged', true, 'transactions', v_transactions);
end;
$$;

create or replace function public.accountbook_update_transaction_v227(
  p_transaction_id uuid,
  p_household_id uuid,
  p_actor_user_id uuid,
  p_actor_kind text,
  p_patch jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.transactions%rowtype;
  v_after public.transactions%rowtype;
begin
  select * into v_before from public.transactions
  where id = p_transaction_id and household_id = p_household_id
  for update;
  if not found then raise exception 'transaction_not_found'; end if;
  if p_patch ? 'user_id' and not exists (
    select 1 from public.household_members
    where household_id = p_household_id
      and user_id = (p_patch->>'user_id')::uuid
      and role not in ('blocked', 'pending')
  ) then raise exception 'spender_not_household_member'; end if;
  if p_patch ? 'type' and p_patch->>'type' not in ('income', 'expense') then raise exception 'invalid_transaction_type'; end if;
  if p_patch ? 'amount' and coalesce((p_patch->>'amount')::numeric, 0) <= 0 then raise exception 'invalid_transaction_amount'; end if;

  update public.transactions
  set type = case when p_patch ? 'type' then p_patch->>'type' else type end,
      amount = case when p_patch ? 'amount' then (p_patch->>'amount')::numeric else amount end,
      category = case when p_patch ? 'category' then p_patch->>'category' else category end,
      memo = case when p_patch ? 'memo' then p_patch->>'memo' else memo end,
      payment_method = case when p_patch ? 'payment_method' then p_patch->>'payment_method' else payment_method end,
      transaction_date = case when p_patch ? 'transaction_date' then (p_patch->>'transaction_date')::date else transaction_date end,
      user_id = case when p_patch ? 'user_id' then (p_patch->>'user_id')::uuid else user_id end
  where id = p_transaction_id
  returning * into v_after;

  insert into public.accountbook_transaction_audit(
    transaction_id, household_id, actor_user_id, actor_kind, action, before_value, after_value
  ) values (
    p_transaction_id, p_household_id, p_actor_user_id,
    left(coalesce(p_actor_kind, 'user'), 30), 'update', to_jsonb(v_before), to_jsonb(v_after)
  );

  return to_jsonb(v_after);
end;
$$;

create or replace function public.accountbook_delete_transaction_v227(
  p_transaction_id uuid,
  p_household_id uuid,
  p_actor_user_id uuid,
  p_actor_kind text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.transactions%rowtype;
begin
  select * into v_before from public.transactions
  where id = p_transaction_id and household_id = p_household_id
  for update;
  if not found then raise exception 'transaction_not_found'; end if;

  insert into public.accountbook_transaction_audit(
    transaction_id, household_id, actor_user_id, actor_kind, action, before_value, after_value
  ) values (
    p_transaction_id, p_household_id, p_actor_user_id,
    left(coalesce(p_actor_kind, 'user'), 30), 'delete', to_jsonb(v_before), null
  );
  delete from public.transactions where id = p_transaction_id;
  return jsonb_build_object('deleted', true, 'id', p_transaction_id);
end;
$$;

create or replace function public.accountbook_bulk_transactions_v227(
  p_transaction_ids uuid[],
  p_household_id uuid,
  p_actor_user_id uuid,
  p_actor_kind text,
  p_patch jsonb default '{}'::jsonb,
  p_delete boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_expected integer := coalesce(cardinality(p_transaction_ids), 0);
  v_found integer := 0;
  v_processed integer := 0;
begin
  if v_expected < 1 or v_expected > 500 then raise exception 'invalid_bulk_size'; end if;
  select count(*) into v_found
  from public.transactions
  where household_id = p_household_id and id = any(p_transaction_ids);
  if v_found <> v_expected then raise exception 'bulk_household_scope_mismatch'; end if;

  foreach v_id in array p_transaction_ids loop
    if coalesce(p_delete, false) then
      perform public.accountbook_delete_transaction_v227(v_id, p_household_id, p_actor_user_id, p_actor_kind);
    else
      perform public.accountbook_update_transaction_v227(v_id, p_household_id, p_actor_user_id, p_actor_kind, coalesce(p_patch, '{}'::jsonb));
    end if;
    v_processed := v_processed + 1;
  end loop;
  return jsonb_build_object('processed', v_processed, 'deleted', coalesce(p_delete, false));
end;
$$;

create or replace function public.accountbook_import_transactions_v227(
  p_household_id uuid,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item jsonb;
  v_inserted integer := 0;
  v_duplicates integer := 0;
begin
  if jsonb_typeof(coalesce(p_rows, '[]'::jsonb)) <> 'array' then raise exception 'rows_must_be_array'; end if;
  if jsonb_array_length(coalesce(p_rows, '[]'::jsonb)) < 1
     or jsonb_array_length(coalesce(p_rows, '[]'::jsonb)) > 1000 then raise exception 'invalid_import_size'; end if;

  for v_item in select value from jsonb_array_elements(p_rows) loop
    if (v_item->>'household_id')::uuid <> p_household_id then raise exception 'import_household_scope_mismatch'; end if;
    if not exists (
      select 1 from public.household_members
      where household_id = p_household_id
        and user_id = (v_item->>'user_id')::uuid
        and role not in ('blocked', 'pending')
    ) then raise exception 'import_spender_not_member'; end if;
    if coalesce((v_item->>'amount')::numeric, 0) <= 0 then raise exception 'invalid_import_amount'; end if;
    if coalesce(v_item->>'type', '') not in ('income', 'expense') then raise exception 'invalid_import_type'; end if;

    insert into public.transactions(
      id, household_id, user_id, type, amount, category, memo, payment_method,
      transaction_date, source, source_user_key, raw_text
    ) values (
      (v_item->>'id')::uuid,
      p_household_id,
      (v_item->>'user_id')::uuid,
      v_item->>'type',
      (v_item->>'amount')::numeric,
      left(coalesce(v_item->>'category', ''), 80),
      left(coalesce(v_item->>'memo', ''), 160),
      left(coalesce(v_item->>'payment_method', ''), 40),
      (v_item->>'transaction_date')::date,
      'my_import',
      left(coalesce(v_item->>'source_user_key', ''), 180),
      left(coalesce(v_item->>'raw_text', ''), 500)
    ) on conflict (id) do nothing;
    if found then v_inserted := v_inserted + 1; else v_duplicates := v_duplicates + 1; end if;
  end loop;

  return jsonb_build_object('inserted', v_inserted, 'duplicates', v_duplicates);
end;
$$;

create or replace function public.accountbook_leave_household_v227(
  p_household_id uuid,
  p_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_deleted integer := 0;
begin
  select role into v_role
  from public.household_members
  where household_id = p_household_id and user_id = p_user_id
  order by case role when 'owner' then 5 when 'admin' then 4 when 'member' then 3 when 'viewer' then 2 else 1 end desc
  limit 1
  for update;

  if v_role is null then raise exception 'household_membership_not_found'; end if;
  if v_role = 'owner' then raise exception 'household_owner_cannot_leave'; end if;

  delete from public.household_members
  where household_id = p_household_id and user_id = p_user_id;
  get diagnostics v_deleted = row_count;
  if v_deleted < 1 then raise exception 'household_leave_not_applied'; end if;

  return jsonb_build_object('left', true, 'deleted_memberships', v_deleted);
end;
$$;

revoke all on function public.accountbook_auth_attempt(text, integer, integer, boolean) from public, anon, authenticated;
revoke all on function public.accountbook_create_local_user_v227(text, text, text, text, integer) from public, anon, authenticated;
revoke all on function public.accountbook_set_local_identity_v227(uuid, text, text, text, integer, boolean) from public, anon, authenticated;
revoke all on function public.accountbook_link_kakao_identity_v227(uuid, text, text) from public, anon, authenticated;
revoke all on function public.accountbook_purge_household_v227(uuid) from public, anon, authenticated;
revoke all on function public.accountbook_replace_budget_plan_v227(uuid, text, jsonb) from public, anon, authenticated;
revoke all on function public.accountbook_apply_recurring_v227(uuid, text) from public, anon, authenticated;
revoke all on function public.accountbook_merge_users_v227(uuid, uuid) from public, anon, authenticated;
revoke all on function public.accountbook_update_transaction_v227(uuid, uuid, uuid, text, jsonb) from public, anon, authenticated;
revoke all on function public.accountbook_delete_transaction_v227(uuid, uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.accountbook_bulk_transactions_v227(uuid[], uuid, uuid, text, jsonb, boolean) from public, anon, authenticated;
revoke all on function public.accountbook_import_transactions_v227(uuid, jsonb) from public, anon, authenticated;
revoke all on function public.accountbook_leave_household_v227(uuid, uuid) from public, anon, authenticated;

grant execute on function public.accountbook_auth_attempt(text, integer, integer, boolean) to service_role;
grant execute on function public.accountbook_create_local_user_v227(text, text, text, text, integer) to service_role;
grant execute on function public.accountbook_set_local_identity_v227(uuid, text, text, text, integer, boolean) to service_role;
grant execute on function public.accountbook_link_kakao_identity_v227(uuid, text, text) to service_role;
grant execute on function public.accountbook_purge_household_v227(uuid) to service_role;
grant execute on function public.accountbook_replace_budget_plan_v227(uuid, text, jsonb) to service_role;
grant execute on function public.accountbook_apply_recurring_v227(uuid, text) to service_role;
grant execute on function public.accountbook_merge_users_v227(uuid, uuid) to service_role;
grant execute on function public.accountbook_update_transaction_v227(uuid, uuid, uuid, text, jsonb) to service_role;
grant execute on function public.accountbook_delete_transaction_v227(uuid, uuid, uuid, text) to service_role;
grant execute on function public.accountbook_bulk_transactions_v227(uuid[], uuid, uuid, text, jsonb, boolean) to service_role;
grant execute on function public.accountbook_import_transactions_v227(uuid, jsonb) to service_role;
grant execute on function public.accountbook_leave_household_v227(uuid, uuid) to service_role;

commit;
