import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";
import worker, { collect, deliverAlerts, summary } from "./worker.mjs";

const sqlite=new DatabaseSync(":memory:");
sqlite.exec(readFileSync(new URL("schema.sql",import.meta.url),"utf8"));
const db={
  prepare(sql) {
    const statement=sqlite.prepare(sql);
    let args=[];
    const api={bind(...values){args=values;return api;},async all(){return {results:statement.all(...args)};},async first(){return statement.get(...args)||null;},run(){const data=statement.run(...args);return {success:true,meta:{changes:data.changes}};}};
    return api;
  },
  async batch(statements) {sqlite.exec("BEGIN");try{const values=[];for(const s of statements)values.push(s.run());sqlite.exec("COMMIT");return values;}catch(e){sqlite.exec("ROLLBACK");throw e;}}
};
let checks=0;
const ok=(value,message)=>{assert.ok(value,message);checks++;};
const eq=(value,expected,message)=>{assert.deepEqual(value,expected,message);checks++;};
const now=new Date();
const env={MONITOR_DB:db,OPS_MONITOR_TOKEN:"sqlite-test-secret",CF_ANALYTICS_TOKEN:"only-a-test",CF_ACCOUNT_ID:"test-account",APP_WORKER_NAME:"test-app",APP_ORIGIN:"https://app.example",SUPABASE_ORG_ID:"test-org",CF_PLAN:"free",SUPABASE_PLAN:"free",PLAN_VERIFIED_AT:now.toISOString(),ACCOUNTBOOK:{async fetch(){return new Response(JSON.stringify({ok:true,metrics:{database_bytes:30*1024**2,connections:5,max_connections:60,cpu_counter:{total:100,idle:80}}}));}}};
const originalFetch=globalThis.fetch;
let graphFails=false, uptimeFails=false, webhookFails=false, tokenExpiresInDays=null, appErrors=0;
const hooks=[];
globalThis.fetch=async(input,init)=>{
  const url=new URL(typeof input==="string"?input:input.url);
  if(url.hostname==="hooks.example") { if(webhookFails) return new Response("down",{status:500}); hooks.push(JSON.parse(String(init?.body))); return new Response("ok"); }
  if(url.hostname==="api.cloudflare.com") {
    if(url.pathname==="/client/v4/user/tokens/verify") return new Response(JSON.stringify({success:true,result:{id:"t",status:"active",expires_on:tokenExpiresInDays===null?null:new Date(Date.now()+tokenExpiresInDays*86400000).toISOString()}}));
    if(String(init?.body).includes('d1AnalyticsAdaptiveGroups')&&!graphFails) return new Response(JSON.stringify({data:{viewer:{accounts:[{usage:[{sum:{rowsRead:450000,rowsWritten:4000}}],storage:[{dimensions:{databaseId:'fixture'},max:{databaseSizeBytes:1048576}}]}]}}}));
    if(graphFails)return new Response('{"errors":[{"message":"test failure"}]}');
    return new Response(JSON.stringify({data:{viewer:{accounts:[{today:[{sum:{requests:20000,errors:0,subrequests:20},dimensions:{status:"success"}}],hour:[{sum:{requests:100,errors:0,subrequests:1}}],app:[{sum:{requests:19000,errors:appErrors,subrequests:19}}]}]}}}));
  }
  return new Response(JSON.stringify(url.pathname==="/ready"?{ready:!uptimeFails}:{alive:true,version:"fixture"}));
};
const req=(path,init={})=>new Request("https://monitor.example"+path,{...init,headers:{authorization:"Bearer sqlite-test-secret","content-type":"application/json",...init.headers}});
try {
  await collect(env,now);
  let result=await summary(env,now.getTime());
  eq(result.states.cloudflare.status,"ok","real SQLite persists successful provider collection");
  eq(result.quotas[1].value,30*1024**2,"database logical size persisted");
  eq(result.quotas[1].limit,500*1024**2,"free project size allowance used");
  eq(result.states.d1.status,"ok","D1 account usage persisted");
  eq(result.quotas.find(q=>q.key==="d1_reads").value,450000,"D1 reads counted across account");
  eq(result.quotas.find(q=>q.key==="d1_writes").limit,100000,"D1 write cap displayed");
  eq(result.quotas.find(q=>q.key==="d1_storage").value,1048576,"D1 conservative daily maximum displayed");
  eq(result.database.cpu_percent,null,"first persisted CPU sample unknown");
  eq(result.quotas.find(q=>q.key==="egress").status,"unknown","missing billing usage cannot appear normal");
  ok(result.unknown.length>0,"global status reports missing data");
  eq(result.application.telemetry_status,"not_connected","missing application telemetry explicitly unobserved");
  ok(result.unknown.includes("앱 요청 표본 미관측 또는 갱신 지연"),"unobserved application is included in global unknown state");
  const monthStart=new Date(now);monthStart.setUTCDate(1);monthStart.setUTCHours(0,0,0,0);
  const monthEnd=new Date(monthStart);monthEnd.setUTCMonth(monthEnd.getUTCMonth()+1);
  for(const key of ["egress","cached_egress","storage"]) eq((await worker.fetch(req("/api/manual",{method:"POST",body:JSON.stringify({key,value:1024,scope:"organization",period_start:monthStart.toISOString(),period_end:monthEnd.toISOString()})}),env,{})).status,200,"normal billing values seeded through authenticated route");
  result=await summary(env);
  ok(result.quotas.every(q=>q.status==="normal"),"all provider and billing quota metrics can be normal in no-telemetry case");
  eq(result.status,"unknown","missing application observations prevent false global normal despite healthy quotas");
  const later=new Date(now.getTime()+300000);
  env.ACCOUNTBOOK.fetch=async()=>new Response(JSON.stringify({ok:true,metrics:{database_bytes:30*1024**2,connections:6,max_connections:60,cpu_counter:{total:200,idle:130}}}));
  await collect(env,later);
  result=await summary(env,later.getTime());
  eq(result.database.cpu_percent,50,"separate persisted samples support CPU delta");
  graphFails=true;
  await collect(env,new Date(later.getTime()+300000));
  result=await summary(env,later.getTime()+300000);
  eq(result.states.cloudflare.status,"error","provider failure stored");
  eq(result.quotas[0].value,null,"past successful quota is not reused as current normal after failure");
  ok(result.states.cloudflare.last_success_at!==null,"last known success retained for diagnosis");
  const telemetry={id:"test-event-123",at:Date.now(),route:"skill",method:"POST",status:200,duration_ms:100,db_count:2,db_ms:30,db_failures:0,outcome:"saved",sample_kind:"random",utterance:"never store"};
  for(let i=0;i<2;i++)eq((await worker.fetch(req("/internal/telemetry",{method:"POST",body:JSON.stringify(telemetry)}),env,{})).status,202,"event insert accepted");
  eq(sqlite.prepare("SELECT COUNT(*) AS n FROM telemetry").get().n,1,"retry deduplicated by event ID");
  const stored=sqlite.prepare("SELECT * FROM telemetry").get();
  ok(!JSON.stringify(stored).includes("never store"),"SQLite payload contains only allowlisted columns");
  result=await summary(env);
  eq(result.application.telemetry_status,"ok","recent accepted application sample is observable");
  sqlite.prepare("UPDATE telemetry SET at=?").run(Date.now()-2*3600000);
  result=await summary(env);
  eq(result.application.telemetry_status,"stale","old application telemetry explicitly stale");
  ok(result.notes.some(note=>note.includes("카카오 p95 표본 부족"))&&!result.unknown.some(item=>item.includes("p95")),"insufficient latency samples are a note, not an unknown item (1.1.0)");
  sqlite.prepare("UPDATE telemetry SET at=?").run(Date.now());
  for(let i=0;i<80;i++) await worker.fetch(req("/internal/telemetry",{method:"POST",body:JSON.stringify({...telemetry,id:`cap-event-${i}`})}),env,{});
  ok(sqlite.prepare("SELECT COUNT(*) AS n FROM telemetry").get().n<=10,"global diagnostic cap protects monitoring storage write budget");
  const login=await worker.fetch(req("/internal/ticket",{method:"POST"}),env,{});
  const {ticket}=await login.json();
  const accept=await worker.fetch(new Request("https://monitor.example/session",{method:"POST",body:new URLSearchParams({ticket})}),env,{});
  eq(accept.status,303,"one-use ticket creates separate monitor session");
  ok(accept.headers.get("set-cookie").includes("HttpOnly")&&accept.headers.get("set-cookie").includes("Secure"),"monitor session protected cookie");
  const replay=await worker.fetch(new Request("https://monitor.example/session",{method:"POST",body:new URLSearchParams({ticket})}),env,{});
  eq(replay.status,401,"one-use ticket cannot be replayed");
  const cookie=accept.headers.get("set-cookie").split(";")[0];
  const csrf=await worker.fetch(new Request("https://monitor.example/api/plans",{method:"POST",headers:{cookie,origin:"https://evil.example"},body:JSON.stringify({cloudflare:"paid",supabase:"pro"})}),env,{});
  eq(csrf.status,403,"cross-origin setting write rejected");
  const internal=await worker.fetch(new Request("https://monitor.example/internal/ticket",{method:"POST",headers:{cookie,origin:"https://monitor.example"}}),env,{});
  eq(internal.status,403,"browser session cannot invoke internal collector routes");
  const page=await worker.fetch(new Request("https://monitor.example/",{headers:{cookie}}),env,{});
  eq(page.status,200,"separate session reads monitoring dashboard");
  eq(page.headers.get("cache-control"),"no-store","monitor pages are never cached");
  const beginning=new Date(now);beginning.setUTCDate(1);beginning.setUTCHours(0,0,0,0);
  const ending=new Date(beginning);ending.setUTCMonth(ending.getUTCMonth()+1);
  const manual=await worker.fetch(req("/api/manual",{method:"POST",body:JSON.stringify({key:"egress",value:1024**3,scope:"organization",period_start:beginning.toISOString(),period_end:ending.toISOString()})}),env,{});
  eq(manual.status,200,"valid organization billing record stored");
  const invalidScope=await worker.fetch(req("/api/manual",{method:"POST",body:JSON.stringify({key:"egress",value:1,scope:"project",period_start:beginning.toISOString(),period_end:ending.toISOString()})}),env,{});
  eq(invalidScope.status,400,"project subtotal cannot masquerade as organization total");
  const plans=await worker.fetch(req("/api/plans",{method:"POST",body:JSON.stringify({cloudflare:"paid",supabase:"pro"})}),env,{});
  eq(plans.status,200,"verified plan metadata stored without billing action");
  result=await summary(env);
  eq(result.quotas.find(q=>q.key==="database_size").limit,null,"Pro physical disk allowance is not compared with logical database size");
  eq(result.plans.cloudflare,"paid","manual plan verification used");
  sqlite.prepare("UPDATE manual_usage SET verified_at=? WHERE key='egress'").run(new Date(Date.now()-2*86400000).toISOString());
  result=await summary(env);
  eq(result.quotas.find(q=>q.key==="egress").status,"unknown","old manual billing record explicitly unknown");
  sqlite.prepare("INSERT INTO telemetry(id,at,route,method,status,duration_ms,db_count,db_ms,db_failures,outcome,sample_kind,slot) VALUES('expired-record',?,'web','GET',200,1,0,0,0,'ok','random','expired-slot')").run(Date.now()-8*86400000);
  sqlite.prepare("INSERT INTO samples(source,bucket,collected_at,payload) VALUES('retention-test',?,?, '{}')").run(new Date(Date.now()-32*86400000).toISOString(),new Date(Date.now()-32*86400000).toISOString());
  const midnight=new Date(now);midnight.setUTCDate(midnight.getUTCDate()+1);midnight.setUTCHours(0,0,0,0);
  await collect(env,midnight);
  eq(sqlite.prepare("SELECT COUNT(*) AS n FROM telemetry WHERE id='expired-record'").get().n,0,"hourly cleanup removes old request observations");
  eq(sqlite.prepare("SELECT COUNT(*) AS n FROM samples WHERE source='retention-test'").get().n,0,"daily cleanup removes old aggregates");
  ok(sqlite.prepare("SELECT COUNT(*) AS n FROM telemetry").get().n>0,"retention cleanup preserves recent request observations");
  // ── 1.1.0 알림 발송·토큰 만료·요금제 만료·오류 건수 ───────────────────────────
  graphFails=false;
  const mails=[];const pending=[];
  const alertEnv={...env,ALERT_EMAIL:{async send(message){mails.push(message);}},ALERT_TO:"ops@example.com",ALERT_FROM:"monitor@app.example",ALERT_WEBHOOK_URL:"https://hooks.example/alert"};
  const runScheduled=async(e,at)=>{await worker.scheduled({scheduledTime:at.getTime()},e,{waitUntil:p=>pending.push(p)});await Promise.all(pending.splice(0));};
  const base=new Date(now);base.setUTCHours(base.getUTCHours()+1,10,0,0);
  uptimeFails=true;
  await runScheduled(alertEnv,base);
  eq(mails.length,1,"critical uptime failure is emailed once");
  eq(hooks.length,1,"webhook receives the same alert");
  ok(mails[0].raw.includes("Subject: =?UTF-8?B?")&&mails[0].raw.includes("Content-Transfer-Encoding: base64")&&mails[0].to==="ops@example.com"&&mails[0].from==="monitor@app.example","alert email is a raw RFC 5322 message from ALERT_FROM to ALERT_TO");
  ok(hooks[0].text.includes("서비스 접속 또는 DB 준비 상태 실패")&&hooks[0].text.includes("/ops-monitor"),"alert text names the failing check and the dashboard");
  ok(sqlite.prepare("SELECT COUNT(*) AS n FROM settings WHERE key LIKE 'alert:%'").get().n>=1,"sent alert remembered for deduplication");
  eq(sqlite.prepare("SELECT status FROM collector_state WHERE name='alerts'").get().status,"ok","alert delivery recorded as a collector state");
  await runScheduled(alertEnv,new Date(base.getTime()+300000));
  eq(mails.length,1,"same critical alert is not resent within 6 hours");
  await runScheduled(alertEnv,new Date(base.getTime()+7*3600000));
  eq(mails.length,2,"still-active critical alert is resent after 6 hours");
  uptimeFails=false;
  await runScheduled(alertEnv,new Date(base.getTime()+7*3600000+300000));
  eq(mails.length,3,"recovery of a critical alert is sent once");
  ok(hooks.at(-1).text.includes("[해소] 서비스 접속 또는 DB 준비 상태 실패"),"recovery message names the recovered alert");
  await runScheduled(alertEnv,new Date(base.getTime()+7*3600000+600000));
  eq(mails.length,3,"nothing new means nothing sent");
  uptimeFails=true; webhookFails=true;
  const failingEnv={...alertEnv,ALERT_EMAIL:{async send(){throw new Error("smtp down");}}};
  await runScheduled(failingEnv,new Date(base.getTime()+8*3600000));
  eq(sqlite.prepare("SELECT error_code FROM collector_state WHERE name='alerts'").get().error_code,"delivery_failed","every channel failing is recorded as delivery_failed");
  eq(sqlite.prepare("SELECT COUNT(*) AS n FROM settings WHERE key LIKE 'alert:%'").get().n,0,"failed delivery leaves no sent record, so the next run retries");
  webhookFails=false;
  await runScheduled(failingEnv,new Date(base.getTime()+8*3600000+300000));
  ok(hooks.at(-1).text.includes("서비스 접속 또는 DB 준비 상태 실패")&&sqlite.prepare("SELECT COUNT(*) AS n FROM settings WHERE key LIKE 'alert:%'").get().n>=1,"retry succeeds through the remaining channel");
  uptimeFails=false;
  await runScheduled(env,new Date(base.getTime()+9*3600000));
  eq(sqlite.prepare("SELECT error_code FROM collector_state WHERE name='alerts'").get().error_code,"not_connected","no alert channel is recorded as not_connected");
  let r=await summary(env,base.getTime()+9*3600000);
  ok(r.unknown.includes("알림 발송 채널 미연결(ALERT_TO 또는 ALERT_WEBHOOK_URL)"),"missing alert channel is a visible unknown item");
  eq(r.delivery.channels.length,0,"summary reports no alert channels");
  ok(r.notes.some(note=>note.includes("p95 표본 부족")),"sparse p95 samples stay a note");
  tokenExpiresInDays=10;
  const hourly=new Date(base);hourly.setUTCHours(hourly.getUTCHours()+10,0,0,0);
  await runScheduled(alertEnv,hourly);
  r=await summary(alertEnv,hourly.getTime());
  ok(r.token.expires_on&&r.token.days_left<=10&&r.token.days_left>=9,"analytics token expiry is collected hourly");
  ok(r.alerts.some(a=>a.title==="Cloudflare 분석 토큰 만료 임박"&&a.status==="warning"),"token expiring within 30 days raises a warning");
  ok(hooks.at(-1).text.includes("분석 토큰 만료 임박"),"token warning is delivered");
  sqlite.prepare("UPDATE settings SET value=? WHERE key='plans'").run(JSON.stringify({cloudflare:"free",supabase:"free",verified_at:new Date(hourly.getTime()-8*86400000).toISOString()}));
  r=await summary(alertEnv,hourly.getTime());
  eq(r.plans.stale,true,"plan record older than 7 days is stale");
  eq(r.plans.cloudflare,"free","stale plan record still names the last verified plan");
  eq(r.quotas.find(q=>q.key==="worker_requests").limit,100000,"stale plan record keeps the last known limit instead of null");
  ok(r.alerts.some(a=>a.title==="요금제 확인 기록 만료")&&r.notes.some(note=>note.includes("요금제 확인 기록이 7일을 넘었습니다")),"stale plan record raises a reminder and a note");
  appErrors=25;
  await collect(alertEnv,new Date(hourly.getTime()+300000));
  r=await summary(alertEnv,hourly.getTime()+300000);
  ok(r.alerts.some(a=>a.title==="앱 Worker 런타임 오류(오늘)"&&a.status==="critical"),"20 or more app runtime errors today is critical even at low traffic");
  appErrors=0;
  const brokenEnv={...alertEnv,ACCOUNTBOOK:{async fetch(){return new Response(JSON.stringify({ok:false,error_code:"metrics_unavailable"}),{status:503});}}};
  await collect(brokenEnv,new Date(hourly.getTime()+600000));
  eq(sqlite.prepare("SELECT error_code FROM collector_state WHERE name='database'").get().error_code,"metrics_unavailable","the app's real database error code survives a 503 (was http_503)");
  // PR #68: a disappearing quota alert is not a recovery if its source cannot be measured.
  sqlite.prepare("DELETE FROM settings WHERE key LIKE 'alert:%'").run();
  sqlite.prepare("UPDATE settings SET value=? WHERE key='plans'").run(JSON.stringify({cloudflare:"free",supabase:"free",verified_at:now.toISOString()}));
  const quotaAt=new Date(now);
  const seedDatabase=(status,payload,at,successAt=at)=>sqlite.prepare("UPDATE collector_state SET status=?,payload=?,last_attempt_at=?,last_success_at=?,error_code=? WHERE name='database'").run(status,JSON.stringify(payload),at.toISOString(),successAt.toISOString(),status==="error"?"metrics_unavailable":null);
  const quotaRecord=()=>sqlite.prepare("SELECT key,value FROM settings WHERE key LIKE 'alert:%'").all().find(row=>JSON.parse(row.value).title==="DB 논리 용량");
  seedDatabase("ok",{database_bytes:499*1024**2},quotaAt);
  const high=await deliverAlerts(alertEnv,quotaAt);
  ok(high.titles.includes("DB 논리 용량")&&quotaRecord(),"critical DB quota is delivered and remembered");
  const criticalRecord=quotaRecord().value;
  for(const missing of ["error","stale","missing-value"]) {
    const at=new Date(quotaAt.getTime()+300000);
    seedDatabase(missing==="error"?"error":"ok",missing==="missing-value"?{}:{database_bytes:499*1024**2},at,missing==="stale"?new Date(at.getTime()-3600000):at);
    const unavailable=await deliverAlerts(alertEnv,at);
    eq(unavailable.recovered,0,`${missing} database evidence never sends a false recovery`);
    eq(quotaRecord()?.value,criticalRecord,`${missing} database evidence preserves the critical dedupe record`);
  }
  const stillHighAt=new Date(quotaAt.getTime()+600000);
  seedDatabase("ok",{database_bytes:499*1024**2},stillHighAt);
  eq((await deliverAlerts(alertEnv,stillHighAt)).sent,0,"a returning critical DB measurement stays deduplicated within six hours");
  const healthyAt=new Date(quotaAt.getTime()+900000);
  seedDatabase("ok",{database_bytes:30*1024**2},healthyAt);
  ok((await summary(alertEnv,healthyAt.getTime())).unknown.length>0,"unrelated unknown collectors remain in the recovery fixture");
  eq((await deliverAlerts(alertEnv,healthyAt)).recovered,1,"fresh normal DB evidence confirms recovery despite unrelated unknown collectors");
  ok(hooks.at(-1).text.includes("[해소] DB 논리 용량")&&!quotaRecord(),"confirmed recovery is delivered before its dedupe record is removed");
  eq((await deliverAlerts(alertEnv,healthyAt)).recovered,0,"confirmed DB recovery is sent only once");
  console.log(`PASS: monitor D1 integration (${checks} checks)`);
} finally {globalThis.fetch=originalFetch;sqlite.close();}
